version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    env_file:
      - .env

  feedback_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: feedback
      POSTGRES_USER: dev_yan_lopes
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  app:
    build: .
    networks:
      - my-network
    depends_on:
      - mailhog
volumes:
  pgdata:

networks:
  my-network:
